package com.junkfood.seal.util

import kotlinx.serialization.Serializable

@Serializable
data class DownloadPreferences(
    val extractAudio: Boolean,
    val createThumbnail: Boolean,
    val downloadPlaylist: Boolean,
    val subdirectoryExtractor: Boolean,
    val subdirectoryPlaylistTitle: Boolean,
    val commandDirectory: String,
    val downloadSubtitle: Boolean,
    val embedSubtitle: Boolean,
    val keepSubtitle: Boolean,
    val subtitleLanguage: String,
    val autoSubtitle: Boolean,
    val autoTranslatedSubtitles: Boolean,
    val convertSubtitle: Int,
    val concurrentFragments: Int,
    val sponsorBlock: Boolean,
    val sponsorBlockCategory: String,
    val cookies: Boolean,
    val aria2c: Boolean,
    val audioFormat: Int,
    val audioQuality: Int,
    val convertAudio: Boolean,
    val formatSorting: Boolean,
    val sortingFields: String,
    val audioConvertFormat: Int,
    val videoFormat: Int,
    val formatIdString: String,
    val videoResolution: Int,
    val privateMode: Boolean,
    val rateLimit: Boolean,
    val maxDownloadRate: String,
    val privateDirectory: Boolean,
    val cropArtwork: Boolean,
    val sdcard: Boolean,
    val sdcardUri: String,
    val embedThumbnail: Boolean,
    val videoClips: List<VideoClip>,
    val splitByChapter: Boolean,
    val debug: Boolean,
    val proxy: Boolean,
    val proxyUrl: String,
    val newTitle: String,
    val userAgentString: String,
    val outputTemplate: String,
    val useDownloadArchive: Boolean,
    val embedMetadata: Boolean,
    val restrictFilenames: Boolean,
    val supportAv1HardwareDecoding: Boolean,
    val forceIpv4: Boolean,
    val mergeAudioStream: Boolean,
    val mergeToMkv: Boolean,
    val useCustomAudioPreset: Boolean,
) {
    companion object {
        val EMPTY =
            DownloadPreferences(
                extractAudio = false,
                createThumbnail = false,
                downloadPlaylist = false,
                subdirectoryExtractor = false,
                subdirectoryPlaylistTitle = false,
                commandDirectory = "",
                downloadSubtitle = false,
                embedSubtitle = false,
                keepSubtitle = false,
                subtitleLanguage = "",
                autoSubtitle = false,
                autoTranslatedSubtitles = false,
                convertSubtitle = 0,
                concurrentFragments = 0,
                sponsorBlock = false,
                sponsorBlockCategory = "",
                cookies = false,
                aria2c = false,
                audioFormat = 0,
                audioQuality = 0,
                convertAudio = false,
                formatSorting = false,
                sortingFields = "",
                audioConvertFormat = 0,
                videoFormat = 0,
                formatIdString = "",
                videoResolution = 0,
                privateMode = false,
                rateLimit = false,
                maxDownloadRate = "",
                privateDirectory = false,
                cropArtwork = false,
                sdcard = false,
                sdcardUri = "",
                embedThumbnail = false,
                videoClips = emptyList(),
                splitByChapter = false,
                debug = false,
                proxy = false,
                proxyUrl = "",
                newTitle = "",
                userAgentString = "",
                outputTemplate = "",
                useDownloadArchive = false,
                embedMetadata = false,
                restrictFilenames = false,
                supportAv1HardwareDecoding = false,
                forceIpv4 = false,
                mergeAudioStream = false,
                mergeToMkv = false,
                useCustomAudioPreset = false,
            )

    }
}
